"""initial_schema

Revision ID: 8626f459da6e
Revises: 
Create Date: 2026-04-27 00:42:22.694717

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8626f459da6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('ix_audit_created_at', 'events', ['created_at'], unique=False, schema='audit')
    op.create_index('ix_audit_event_type', 'events', ['event_type'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_events_created_at'), 'events', ['created_at'], unique=False, schema='audit')
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('work_hours_start', sa.String(length=5), nullable=False),
    sa.Column('work_hours_end', sa.String(length=5), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    op.create_table('edge_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_pseudo_id', sa.UUID(), nullable=False),
    sa.Column('target_pseudo_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='features'
    )
    op.create_index('ix_edge_window', 'edge_signals', ['window_start'], unique=False, schema='features')
    op.create_table('feature_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudo_id', sa.UUID(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feature_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_imputed', sa.Boolean(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='features'
    )
    op.create_index('ix_fv_pseudo_id_window', 'feature_vectors', ['pseudo_id', 'window_start'], unique=False, schema='features')
    op.create_table('burnout_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('pseudo_id', sa.UUID(), nullable=False),
    sa.Column('burnout_score', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('cascade_risk', sa.Float(), nullable=True),
    sa.Column('cascade_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='scores'
    )
    op.create_index('ix_bs_pseudo_id', 'burnout_scores', ['pseudo_id'], unique=False, schema='scores')
    op.create_index('ix_bs_run_id', 'burnout_scores', ['run_id'], unique=False, schema='scores')
    op.create_table('scoring_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('edge_count', sa.Integer(), nullable=True),
    sa.Column('sources_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='scores'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_runs', schema='scores')
    op.drop_index('ix_bs_run_id', table_name='burnout_scores', schema='scores')
    op.drop_index('ix_bs_pseudo_id', table_name='burnout_scores', schema='scores')
    op.drop_table('burnout_scores', schema='scores')
    op.drop_index('ix_fv_pseudo_id_window', table_name='feature_vectors', schema='features')
    op.drop_table('feature_vectors', schema='features')
    op.drop_index('ix_edge_window', table_name='edge_signals', schema='features')
    op.drop_table('edge_signals', schema='features')
    op.drop_table('orgs', schema='config')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='events', schema='audit')
    op.drop_index('ix_audit_event_type', table_name='events', schema='audit')
    op.drop_index('ix_audit_created_at', table_name='events', schema='audit')
    op.drop_table('events', schema='audit')
    # ### end Alembic commands ###
