"""extend audit event with tamper-evident hash chain

Revision ID: 8690ad47d1c4
Revises: 893cdc022dcc
Create Date: 2026-05-29 15:28:11.580848

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8690ad47d1c4'
down_revision: Union[str, None] = '893cdc022dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('actor_id', sa.UUID(), nullable=False), schema='audit')
    op.add_column('events', sa.Column('action', sa.String(length=50), nullable=False), schema='audit')
    op.add_column('events', sa.Column('resource_type', sa.String(length=50), nullable=False), schema='audit')
    op.add_column('events', sa.Column('resource_id', sa.UUID(), nullable=True), schema='audit')
    op.add_column('events', sa.Column('prev_hash', sa.String(length=64), nullable=True), schema='audit')
    op.add_column('events', sa.Column('event_hash', sa.String(length=64), nullable=False), schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_hash', schema='audit')
    op.drop_column('events', 'prev_hash', schema='audit')
    op.drop_column('events', 'resource_id', schema='audit')
    op.drop_column('events', 'resource_type', schema='audit')
    op.drop_column('events', 'action', schema='audit')
    op.drop_column('events', 'actor_id', schema='audit')
    # ### end Alembic commands ###
