"""enrollment_and_profiles

Revision ID: 893cdc022dcc
Revises: 8626f459da6e
Create Date: 2026-04-27 01:11:54.687022

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '893cdc022dcc'
down_revision: Union[str, None] = '8626f459da6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudo_id', sa.UUID(), nullable=False),
    sa.Column('display_name_hash', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('work_hours_start', sa.String(length=5), nullable=False),
    sa.Column('work_hours_end', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo_id'),
    schema='config'
    )
    op.create_index('ix_emp_pseudo_id', 'employees', ['pseudo_id'], unique=True, schema='config')
    op.create_index('ix_emp_team_id', 'employees', ['team_id'], unique=False, schema='config')
    op.create_table('employee_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudo_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('avg_score_30d', sa.Float(), nullable=True),
    sa.Column('score_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cascade_exposure_count', sa.Integer(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('seed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo_id'),
    schema='scores'
    )
    op.create_index('ix_ep_pseudo_id', 'employee_profiles', ['pseudo_id'], unique=True, schema='scores')
    op.create_index('ix_ep_team_id', 'employee_profiles', ['team_id'], unique=False, schema='scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ep_team_id', table_name='employee_profiles', schema='scores')
    op.drop_index('ix_ep_pseudo_id', table_name='employee_profiles', schema='scores')
    op.drop_table('employee_profiles', schema='scores')
    op.drop_index('ix_emp_team_id', table_name='employees', schema='config')
    op.drop_index('ix_emp_pseudo_id', table_name='employees', schema='config')
    op.drop_table('employees', schema='config')
    # ### end Alembic commands ###
